### ISSUE TITLE
Error in running the example: X_RF() and EstimateCate()

### ISSUE THREAD

**Issue by Morph0124** [forestry-labs/causalToolbox#1]
I was running the example on windows. When I used the X_RF() and EstimateCate() function, I got the error below. I am running on Windows and the "causalToolbox" version is 0.0.2.0. Is the windows operation system causing the error? Any advise would be helpful. Thanks!
![image](https://user-images.githubusercontent.com/53892778/115948028-4323cc00-a4fe-11eb-8e78-f2c3a33311cb.png)
![image](https://user-images.githubusercontent.com/53892778/115948036-47e88000-a4fe-11eb-87c7-c023b69c5f14.png)

**Comment by theo-s** [comment]
This should be fixed in Version `0.0.2.1`
