### ISSUE TITLE
CateCI doesn't work for RFs

### ISSUE THREAD

**Issue by siyunyang** [forestry-labs/causalToolbox#3]
Hello thank you for creating this wonderful toolbox. I was trying to implement your example code to calculate the CI of X_RF by "xl_ci_rf <- CateCI(xl_rf, feature_test, B = 500)" but got the following error message.
Error in CateCI(xl_rf, feature_test, B = 500) :
  no slot of name "forest" for this object of class "X_RF"

Thank you!

**Comment by theo-s** [comment]
I have added a fix for this in Version `0.0.2.1`, this fixes the error for me.

**Comment by siyunyang** [comment]
I updated to the Version 0.0.2.1, and ran the code on your example data and my own data. Both got the following error:
xl_rf <- X_RF(feat = feature_train, tr = w_train, yobs = yobs_train)
xl_ci_rf <- CateCI(xl_rf, feature_test, B = 50)
Error in CateCI(xl_rf, feature_test, B = 50) :
  one of the groups might be too small to
               do valid inference.

Same error was also found for M_RF.

**Comment by JasjeetSekhon** [comment]
What version of Rforestey do you have installed?

**Comment by siyunyang** [comment]
I am using Rforestry version ‘0.9.0.92’
