### ISSUE TITLE
Package cannot be installed

### ISSUE THREAD

**Issue by Quaterion** [forestry-labs/causalToolbox#7]
I follow the installation guide and exectute the following commands:

    if (!require("devtools")) install.packages("devtools")
    devtools::install_github("forestry-labs/causalToolbox")

I get the following error message: 

    Downloading GitHub repo forestry-labs/causalToolbox@HEAD
    Fehler: Failed to install 'causalToolbox' from GitHub:
      HTTP error 404.
      Not Found

      Did you spell the repo owner (`forestry-labs`) and repo name (`Rforestry`) correctly?
      - If spelling is correct, check that you have the required permissions to access the repo.

The following code shows that everything is installed that is required: 

    devtools::has_devel()
    Your system is ready to build packages!

I use R version 4.2.2 with Rtools 42 and Windows 10.

**Comment by theo-s** [comment]
Thanks for bringing this to my attention, we recently changed the structure of the `Rforestry` repo, so installing `Rforestry` using `devtools` will have to use a different path now. 

I will update the dependency in `causalToolbox` to reflect this change, in the meantime, I recommend installing `Rforestry` from CRAN. 

This can be done using `install.packages("Rforestry")`

**Comment by victorfeagins** [comment]
Are the steps to run `install.packages("Rforestry")` and then to run `devtools::install_github("soerenkuenzel/causalToolbox")` and to skip updating Rforestry?
